[package]
name = "reqwest-test"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
futures = "0.3.31"
http = "1.2.0"
reqwest = "0.12.9"
reqwest-middleware = "0.4.0"
tokio = {version = "1.42.0", features = ["full"] }
url = "2.5.4"
