[package]
name = "mcp-client-test-darinkishore"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.4", features = ["derive"] }
mcp_client_rs = "0.1.7"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
